import type { Metadata } from "next";
import "./globals.css";
import { Barl, Rob, BarlowCon200, BarlowCon600 } from "./Fonts/fonts";
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${BarlowCon200.className} font-extrabold`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
